[workspace]
members = [
	"circuits",
	"core",
	"integration-helpers"
]

[profile.bench]
opt-level = 3 # Full optimizations
lto = true

[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std" }
ark-relations =  { git = "https://github.com/arkworks-rs/snark"}