[package]
name = "darkpool-relayer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
base64 = { version = "0.13" }
clap = { version = "3.2.8", features = ["derive"] }
crossbeam = { version = "0.8.1" }
ed25519-dalek = { version = "1.0.1" }
futures = { version = "0.3.21" }
libp2p = { version = "0.46.1", features = ["tcp-tokio", "mdns"] }
lru = { version = "0.7.7" }
once_cell = "1.5"
serde = "1.0.139"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
