[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bn254 = { version = "0.3" }
ark-crypto-primitives = { version = "0.3", features = ["r1cs"] }
ark-ec = { version = "0.3" }
ark-ed-on-bn254 = { version = "0.3" }
ark-ff = { version = "0.3" }
ark-groth16 = { version = "0.3" }
ark-relations = { version = "0.3" }
ark-r1cs-std = { version = "0.3" }
ark-sponge = { version = "0.3" }

num-bigint = { version = "0.4" }
rand = { version = "0.8" }
