[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"
curve25519-dalek = "2"
mpc-ristretto = { git = "https://github.com/renegade-fi/MPC-Ristretto" }
mpc-bulletproof = { git = "https://github.com/renegade-fi/mpc-bulletproof" }
num-bigint = { version = "0.4", features = ["rand"] }
rand = { version = "0.8" }

[dev-dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-sponge = { git = "https://github.com/arkworks-rs/sponge" }
clap = { version = "4.0", features = ["derive"] }
colored = "2"
ctor = "0.1"
criterion = { version = "0.4" } 
dns-lookup = "1.0"
integration-helpers = { path = "../integration-helpers" }
inventory = "0.3"
rand = "0.8"
rand_core = "0.5"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
