[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[profile.bench]
opt-level = 3 # Full optimizations
lto = true

[[bench]]
name = "valid_match_benchmark"
harness = false

[dependencies]
ark-bn254 = { version = "0.3" }
ark-crypto-primitives = { version = "0.3", features = ["r1cs"] }
ark-ec = { version = "0.3" }
ark-ed-on-bn254 = { version = "0.3" }
ark-ff = { version = "0.3" }
ark-groth16 = { version = "0.3" }
ark-relations = { version = "0.3" }
ark-r1cs-std = { version = "0.3" }
ark-sponge = { version = "0.3" }

criterion = { version = "0.3" }
num-bigint = { version = "0.4" }
rand = { version = "0.8" }
