[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "valid_match_small_benchmark"
harness = false

[dependencies]
ark-bn254 = { version = "0.3" }
ark-ec = { version = "0.3" }
ark-ed-on-bn254 = { version = "0.3" }
ark-ff = { version = "0.3" }
ark-groth16 = { version = "0.3" }
ark-relations = { version = "0.3" }
ark-r1cs-std = { version = "0.3" }
ark-sponge = { version = "0.3" }

arkworks-native-gadgets = { version = "1.0" }
arkworks-r1cs-gadgets = { version = "1.0" }
arkworks-utils = { version = "0.4" }

criterion = { version = "0.3" }
num-bigint = { version = "0.4" }
rand = { version = "0.8" }
